// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	netlink "github.com/vishvananda/netlink"
)

// RdmaBasicOps is an autogenerated mock type for the RdmaBasicOps type
type RdmaBasicOps struct {
	mock.Mock
}

// GetRdmaDevicesForPcidev provides a mock function with given fields: pcidevName
func (_m *RdmaBasicOps) GetRdmaDevicesForPcidev(pcidevName string) []string {
	ret := _m.Called(pcidevName)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pcidevName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// RdmaLinkByName provides a mock function with given fields: name
func (_m *RdmaBasicOps) RdmaLinkByName(name string) (*netlink.RdmaLink, error) {
	ret := _m.Called(name)

	var r0 *netlink.RdmaLink
	if rf, ok := ret.Get(0).(func(string) *netlink.RdmaLink); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*netlink.RdmaLink)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RdmaLinkSetNsFd provides a mock function with given fields: link, fd
func (_m *RdmaBasicOps) RdmaLinkSetNsFd(link *netlink.RdmaLink, fd uint32) error {
	ret := _m.Called(link, fd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*netlink.RdmaLink, uint32) error); ok {
		r0 = rf(link, fd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RdmaSystemGetNetnsMode provides a mock function with given fields:
func (_m *RdmaBasicOps) RdmaSystemGetNetnsMode() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RdmaSystemSetNetnsMode provides a mock function with given fields: newMode
func (_m *RdmaBasicOps) RdmaSystemSetNetnsMode(newMode string) error {
	ret := _m.Called(newMode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(newMode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
