// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/containernetworking/plugins/pkg/ns"
	"github.com/k8snetworkplumbingwg/rdma-cni/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQoSManager creates a new instance of MockQoSManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQoSManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQoSManager {
	mock := &MockQoSManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQoSManager is an autogenerated mock type for the QoSManager type
type MockQoSManager struct {
	mock.Mock
}

type MockQoSManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQoSManager) EXPECT() *MockQoSManager_Expecter {
	return &MockQoSManager_Expecter{mock: &_m.Mock}
}

// GetRdmaDevQoS provides a mock function for the type MockQoSManager
func (_mock *MockQoSManager) GetRdmaDevQoS(rdmaDev string) (types.RDMAQoS, error) {
	ret := _mock.Called(rdmaDev)

	if len(ret) == 0 {
		panic("no return value specified for GetRdmaDevQoS")
	}

	var r0 types.RDMAQoS
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (types.RDMAQoS, error)); ok {
		return returnFunc(rdmaDev)
	}
	if returnFunc, ok := ret.Get(0).(func(string) types.RDMAQoS); ok {
		r0 = returnFunc(rdmaDev)
	} else {
		r0 = ret.Get(0).(types.RDMAQoS)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(rdmaDev)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQoSManager_GetRdmaDevQoS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRdmaDevQoS'
type MockQoSManager_GetRdmaDevQoS_Call struct {
	*mock.Call
}

// GetRdmaDevQoS is a helper method to define mock.On call
//   - rdmaDev string
func (_e *MockQoSManager_Expecter) GetRdmaDevQoS(rdmaDev interface{}) *MockQoSManager_GetRdmaDevQoS_Call {
	return &MockQoSManager_GetRdmaDevQoS_Call{Call: _e.mock.On("GetRdmaDevQoS", rdmaDev)}
}

func (_c *MockQoSManager_GetRdmaDevQoS_Call) Run(run func(rdmaDev string)) *MockQoSManager_GetRdmaDevQoS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQoSManager_GetRdmaDevQoS_Call) Return(rDMAQoS types.RDMAQoS, err error) *MockQoSManager_GetRdmaDevQoS_Call {
	_c.Call.Return(rDMAQoS, err)
	return _c
}

func (_c *MockQoSManager_GetRdmaDevQoS_Call) RunAndReturn(run func(rdmaDev string) (types.RDMAQoS, error)) *MockQoSManager_GetRdmaDevQoS_Call {
	_c.Call.Return(run)
	return _c
}

// SetRdmaDevQoS provides a mock function for the type MockQoSManager
func (_mock *MockQoSManager) SetRdmaDevQoS(targetNs ns.NetNS, rdmaDev string, qos types.RDMAQoS) error {
	ret := _mock.Called(targetNs, rdmaDev, qos)

	if len(ret) == 0 {
		panic("no return value specified for SetRdmaDevQoS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ns.NetNS, string, types.RDMAQoS) error); ok {
		r0 = returnFunc(targetNs, rdmaDev, qos)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQoSManager_SetRdmaDevQoS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRdmaDevQoS'
type MockQoSManager_SetRdmaDevQoS_Call struct {
	*mock.Call
}

// SetRdmaDevQoS is a helper method to define mock.On call
//   - targetNs ns.NetNS
//   - rdmaDev string
//   - qos types.RDMAQoS
func (_e *MockQoSManager_Expecter) SetRdmaDevQoS(targetNs interface{}, rdmaDev interface{}, qos interface{}) *MockQoSManager_SetRdmaDevQoS_Call {
	return &MockQoSManager_SetRdmaDevQoS_Call{Call: _e.mock.On("SetRdmaDevQoS", targetNs, rdmaDev, qos)}
}

func (_c *MockQoSManager_SetRdmaDevQoS_Call) Run(run func(targetNs ns.NetNS, rdmaDev string, qos types.RDMAQoS)) *MockQoSManager_SetRdmaDevQoS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ns.NetNS
		if args[0] != nil {
			arg0 = args[0].(ns.NetNS)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.RDMAQoS
		if args[2] != nil {
			arg2 = args[2].(types.RDMAQoS)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQoSManager_SetRdmaDevQoS_Call) Return(err error) *MockQoSManager_SetRdmaDevQoS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQoSManager_SetRdmaDevQoS_Call) RunAndReturn(run func(targetNs ns.NetNS, rdmaDev string, qos types.RDMAQoS) error) *MockQoSManager_SetRdmaDevQoS_Call {
	_c.Call.Return(run)
	return _c
}
