// Copyright 2025 NVIDIA CORPORATION & AFFILIATES
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	ns "github.com/containernetworking/plugins/pkg/ns"
	mock "github.com/stretchr/testify/mock"
)

// RdmaManager is an autogenerated mock type for the RdmaManager type
type RdmaManager struct {
	mock.Mock
}

// GetRdmaDevsForPciDev provides a mock function with given fields: pciDev
func (_m *RdmaManager) GetRdmaDevsForPciDev(pciDev string) ([]string, error) {
	ret := _m.Called(pciDev)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pciDev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pciDev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSystemRdmaMode provides a mock function with given fields:
func (_m *RdmaManager) GetSystemRdmaMode() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MoveRdmaDevToNs provides a mock function with given fields: rdmadev, netNs
func (_m *RdmaManager) MoveRdmaDevToNs(rdmadev string, netNs ns.NetNS) error {
	ret := _m.Called(rdmadev, netNs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ns.NetNS) error); ok {
		r0 = rf(rdmadev, netNs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetSystemRdmaMode provides a mock function with given fields: mode
func (_m *RdmaManager) SetSystemRdmaMode(mode string) error {
	ret := _m.Called(mode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
